# Generated by Django 2.2.4 on 2019-08-16 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('price', models.PositiveIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guide_tours', to='place.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guide_tours', to='place.Country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_tours', to='client.Client')),
            ],
        ),
    ]
